version: "3.10"

services:
  taipy-app:
    build: .
    container_name: taipy_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
